### ISSUE TITLE
Example with external api

### ISSUE THREAD

**Issue by theprobugmaker** [j0lv3r4/next-authentication#22]
Is it possible to create an example using an external api instead of next api routes? With external API I mean a regular nodejs api running in another port but in the same domain, it can be using passport or anything simple, I just want to see how the communication would be like.

By the way, good job with the project :heart:  Keep it up the good work.

**Comment by juanbzz** [comment]
Hey @zefexdeveloper, I need to figure out how that would work with this library since next-authentication is a replacement for Passport on the Next.js side. Of course, Passport is way better since next-authentication is far long from v1.0, but let me think of something and I will ping you.

**Comment by theprobugmaker** [comment]
@j0lv3r4 Thank you very much. I like to use passport cause it has support already for social networking and stuff. The truth is that I would like to see how it would work with an external api, like the server is running on another port and the client (next) is communicating with it, logging in, registering, logging out and validating the cookie if the user is actually authenticated in a page, etc
